// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPlugin(arg1, arg2) {
  return window['go']['main']['App']['AddPlugin'](arg1, arg2);
}

export function GetAppIcon(arg1) {
  return window['go']['main']['App']['GetAppIcon'](arg1);
}

export function GetForegroundHWND() {
  return window['go']['main']['App']['GetForegroundHWND']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function LaunchApp(arg1) {
  return window['go']['main']['App']['LaunchApp'](arg1);
}

export function ListPlugins() {
  return window['go']['main']['App']['ListPlugins']();
}

export function RemovePlugin(arg1) {
  return window['go']['main']['App']['RemovePlugin'](arg1);
}

export function ResizeWindow(arg1, arg2) {
  return window['go']['main']['App']['ResizeWindow'](arg1, arg2);
}

export function RunPlugins(arg1) {
  return window['go']['main']['App']['RunPlugins'](arg1);
}

export function SearchApps(arg1) {
  return window['go']['main']['App']['SearchApps'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function Shutdown() {
  return window['go']['main']['App']['Shutdown']();
}

export function TogglePlugin(arg1) {
  return window['go']['main']['App']['TogglePlugin'](arg1);
}

export function ToggleWindow() {
  return window['go']['main']['App']['ToggleWindow']();
}
