// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddPlugin(arg1:string,arg2:string):Promise<string>;

export function GetAppIcon(arg1:string):Promise<string>;

export function GetForegroundHWND():Promise<number>;

export function HideWindow():Promise<void>;

export function LaunchApp(arg1:string):Promise<string>;

export function ListPlugins():Promise<Array<main.PluginInfo>>;

export function RemovePlugin(arg1:number):Promise<string>;

export function ResizeWindow(arg1:number,arg2:number):Promise<void>;

export function RunPlugins(arg1:string):Promise<Array<main.PluginEntry>>;

export function SearchApps(arg1:string):Promise<Array<main.AppEntry>>;

export function ShowWindow():Promise<void>;

export function Shutdown():Promise<void>;

export function TogglePlugin(arg1:number):Promise<string>;

export function ToggleWindow():Promise<void>;
